---
- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
 
- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
 
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest
  
- name: "set the ansible repo"
  apt_repository:
    repo: "ppa:ansible/ansible"

- name: install packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - nodejs
    - npm
    - python-pip
    - git
    - pwgen
    - vim

- name: install npm-global
  npm:
    name: "npm"
    global: yes

- name: install pip packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker
    - ansible
    - docker-compose

- name: clone awx repo
  git:
    repo: https://github.com/ansible/awx.git
    dest: /root/awx
    depth: 50

- name: copy inventory file
  copy:
    src: inventory
    dest: /root/awxsetup/inventory
- name: Move role directory contents
  command: cp -r /root/awx/installer/roles/* /root/awxsetup/roles/    

